version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

exclude_patterns = [
  "**/node_modules/",
  "dist/**",
  "src/examples/**"
]