version = 1

exclude_patterns = [
  "**/node_modules/",
  "dist/**",
  "src/examples/**",
  "src/demo/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"
