name: Snyk Security Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest
    name: Snyk Security Scan
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_SECRET }}
        with:
          args: --severity-threshold=high
